<!DOCTYPE html>

<html>
    <head>
        <meta property="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->baseUrl; ?>/backoffice/resources/icones/faviconTurbine.png"/>
        <title>Turbine Login</title>
        <script src="<?php echo $this->ang?>/angular.min.js"></script>
        <script src="<?php echo $this->ang?>/angular-cookies.min.js"></script>
        <!-- <script src="<?php echo $this->extJsPath; ?>/<?php echo $this->extJsScript; ?>"></script> -->
        <link rel="stylesheet" href="<?php echo $this->ui; ?>css/turbine.css">
        <link rel="stylesheet" href="<?php echo $this->ui; ?>css/login.css">
    </head>
    <body ng-app="turbine" ng-controller="LoginController">
        <div class="loaderOuter" style="display: none;">
            <div class="loading">
                <div class="bullet"></div>
                <div class="bullet"></div>
                <div class="bullet"></div>
                <div class="bullet"></div>
            </div>
        </div>
        <div id="wrapper" style="opacity: 1;">
            <div class="loginCont">
                <div class="loginInnr_cont" id="login" style="opacity: 1; top: 0px;">
                    <div class="loginLogo"><img src="<?php echo $this->ui;?>image/logo-turbine-center.png?>" alt="#"></div>
                    <form class="loginInnr_box" ng-submit="processForm()">
                        <h2><strong>Welcome</strong>, Please login</h2>                        
                        <div class="errors" ng-show="hasError">
                            <span class="error_span"></span>
                            <p>{{error_message}}</p>
                        </div>
                        <ul>
                            <li class="clearfix">
                                <strong>Email*</strong>
                                <input type="text" placeholder="Username" ng-class="input_key" ng-required ng-model="formData.PHP_AUTH_USER">
                            </li>
                            <li class="clearfix">
                                <strong>Password*</strong>
                                <input type="password" placeholder="Password" ng-class="input_key" ng-required ng-model="formData.PHP_AUTH_PW">
                            </li>
                            <li class="clearfix"> 
                                <div class="loginSubmit">
                                    <input type="submit" class="submit_login_form" value="Log In">
                                </div>
                            </li>
                        </ul>
                        <small class="loginCopyRight">Copyright Turbine . 2016 </small> 
                    </form>
                </div>  
            </div>
        </div>
    </body>
    <script>
        var app = angular.module('turbine', ['ngCookies']);
        app.controller('LoginController', [ '$scope','$http', '$cookies', '$cookieStore', function($scope, $http, $cookies, $cookieStore) {
            $scope.hasError = false;
            $scope.error_message = '';
            $scope.formData = {};

            $scope.processForm = function(){
                $http({
                    method  : 'POST',
                    url     : '/api/v1/auth/oauth2/generate',
                    data    : $scope.formData,
                    headers : {'Content-Type': 'application/x-www-form-urlencoded'} 
                })
                .then(
                    function(data) {
                        console.log(data);
                        data = data.data;
                        if (data.success) {
                            var expirationDate = data.token.createTime + data.token.lifetime;
                            expirationDate = new Date(expirationDate * 1000);
                            $cookies["accessToken"] = data.token.access_token;
                            $cookies["refreshToken"] = data.token.refresh_token;
                            $cookies["current"] = data.currentUser.name;
                            //document.cookie = "accessToken = "+data.token.access_token+"; expires="+expirationDate;
                            //document.cookie = "refreshToken = "+data.token.refresh_token+";";
                            //document.cookie = "current = "+ data.currentUser.name+";";
                            //Ext.util.Cookies.set("accessToken", data.token.access_token, expirationDate);
                            //Ext.util.Cookies.set("refreshToken", data.token.refresh_token);
                            //Ext.util.Cookies.set("currentUser", data.currentUser.name);
                            window.location.href = "/backoffice";
                        }
                    },
                    function(data){
                        console.log(data);
                        $scope.hasError = true;
                        $scope.error_message = data.statusText;
                    }
                );
            }
        }]);
    </script>
</html>